# Generated by Django 4.2.5 on 2023-09-13 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_evento_usuario_alter_evento_data_criacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="local",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Local:"
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário:",
            ),
        ),
    ]
